# Generated by Django 5.2.8 on 2026-01-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_alter_userprofile_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    (
                        "view_all_user_accounts",
                        "Can view all user accounts university-wide",
                    ),
                    (
                        "view_user_accounts_assigned_location",
                        "Can view user accounts assigned to their locations",
                    ),
                ],
                "verbose_name": "User Profile",
            },
        ),
    ]
