# Generated by Django 5.2.8 on 2026-03-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0004_userprofile_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="person",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
