# Generated by Django 5.2.8 on 2026-04-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0005_remove_userprofile_person_alter_userprofile_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    (
                        "view_user_accounts",
                        "Can view user accounts in assigned locations",
                    ),
                    (
                        "view_all_user_accounts",
                        "Can view all user accounts university-wide",
                    ),
                    ("create_user_accounts", "Can create user accounts"),
                    ("edit_user_accounts", "Can edit user accounts"),
                    ("delete_user_accounts", "Can delete user accounts"),
                    ("assign_user_locations", "Can assign locations to user accounts"),
                    ("assign_user_roles", "Can assign roles to user accounts"),
                    ("view_roles", "Can view roles"),
                    ("create_roles", "Can create roles"),
                    ("edit_roles", "Can edit roles"),
                    ("delete_roles", "Can delete roles"),
                    ("assign_permissions_to_roles", "Can assign permissions to roles"),
                ],
                "verbose_name": "User Profile",
            },
        ),
    ]
