# Generated by Django 5.2.8 on 2026-05-03 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_role_metadata(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    RoleMetadata = apps.get_model("user_management", "RoleMetadata")

    existing_group_ids = set(RoleMetadata.objects.values_list("group_id", flat=True))
    RoleMetadata.objects.bulk_create(
        [RoleMetadata(group_id=group.id) for group in Group.objects.exclude(id__in=existing_group_ids)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user_management", "0006_add_domain_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_role_metadata",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_metadata",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Metadata",
                "verbose_name_plural": "Role Metadata",
            },
        ),
        migrations.RunPython(backfill_role_metadata, migrations.RunPython.noop),
    ]
