# Generated by Django 5.2.8 on 2026-06-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
