# Generated by Django 6.0.1 on 2026-01-20 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FIXED_ASSET", "Fixed Asset"),
                            ("CONSUMABLE", "Consumable"),
                        ],
                        help_text="Financial nature. Set at parent level, can be overridden.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tracking_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INDIVIDUAL", "Individual Tracking (Serial/QR)"),
                            ("BATCH", "Batch Tracking (FIFO/Expiry)"),
                        ],
                        help_text="Operational nature. Assigned at subcategory level.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "default_depreciation_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Assigned at parent level for Fixed Assets. Inherited by subcategories.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "unique_together": {("parent_category", "name")},
            },
        ),
        migrations.CreateModel(
            name="CategoryRateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_history",
                        to="inventory.category",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name must be unique",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated if not provided",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("DEPARTMENT", "Department"),
                            ("BUILDING", "Building"),
                            ("STORE", "Store"),
                            ("ROOM", "Room"),
                            ("LAB", "Lab"),
                            ("JUNKYARD", "Junkyard"),
                            ("OFFICE", "Office"),
                            ("AV_HALL", "AV Hall"),
                            ("AUDITORIUM", "Auditorium"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_store", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("in_charge", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_standalone",
                    models.BooleanField(
                        default=False,
                        help_text="If true, this location can have sub-locations and will get a main store",
                    ),
                ),
                ("is_auto_created", models.BooleanField(default=False)),
                (
                    "is_main_store",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the main store for its parent standalone location",
                    ),
                ),
                (
                    "hierarchy_level",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                (
                    "hierarchy_path",
                    models.CharField(blank=True, editable=False, max_length=765),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auto_created_store",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_location_ref",
                        to="inventory.location",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_locations",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "manage_all_locations",
                        "Can access all locations regardless of hierarchy",
                    ),
                    ("create_standalone_location", "Can create standalone locations"),
                    ("create_store_location", "Can create store locations"),
                ],
                "indexes": [
                    models.Index(fields=["code"], name="inventory_l_code_55fb32_idx"),
                    models.Index(
                        fields=["location_type"], name="inventory_l_locatio_88dd59_idx"
                    ),
                    models.Index(
                        fields=["is_store"], name="inventory_l_is_stor_c693f2_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="inventory_l_is_acti_a5da3a_idx"
                    ),
                    models.Index(
                        fields=["is_standalone"], name="inventory_l_is_stan_daf599_idx"
                    ),
                    models.Index(
                        fields=["is_main_store"], name="inventory_l_is_main_1b02c5_idx"
                    ),
                    models.Index(
                        fields=["hierarchy_level"],
                        name="inventory_l_hierarc_0241ae_idx",
                    ),
                    models.Index(
                        fields=["hierarchy_path"], name="inventory_l_hierarc_95ee40_idx"
                    ),
                ],
            },
        ),
    ]
