# Generated by Django 5.2.8 on 2026-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated if not provided",
                max_length=255,
                unique=True,
            ),
        ),
    ]
