# Generated by Django 6.0.1 on 2026-01-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('FIXED_ASSET', 'Fixed Asset'), ('CONSUMABLE', 'Consumable')], help_text='Financial nature. Set at parent level, can be overridden.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assigned at parent level for Fixed Assets. Inherited by subcategories.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='tracking_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual Tracking (Serial/QR)'), ('BATCH', 'Batch Tracking (FIFO/Expiry)')], help_text='Operational nature. Assigned at subcategory level.', max_length=20, null=True),
        ),
    ]
