# Generated by Django 5.2.8 on 2026-01-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_inspectioncertificate_alter_category_category_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
