# Generated by Django 5.2.8 on 2026-01-21 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_item_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="instances",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="item",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="quantity",
        ),
        migrations.AddField(
            model_name="stockentry",
            name="issued_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Person receiving the items if issued to a person.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_entries",
                to="inventory.person",
            ),
        ),
        migrations.CreateModel(
            name="StockEntryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.itembatch",
                    ),
                ),
                (
                    "instances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stock_entry_items",
                        to="inventory.iteminstance",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.item"
                    ),
                ),
                (
                    "stock_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.stockentry",
                    ),
                ),
            ],
        ),
    ]
