# Generated by Django 5.2.8 on 2026-01-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_person_remove_stockentry_batch_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockentry",
            name="inspection_certificate",
        ),
        migrations.DeleteModel(
            name="InspectionCertificate",
        ),
    ]
