# Generated by Django 5.2.8 on 2026-01-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_stockentry_inspection_certificate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockentry",
            options={
                "permissions": [
                    ("acknowledge_stockentry", "Can acknowledge stock receipt entries")
                ]
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Must be a sub-category (has a parent category)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.category",
            ),
        ),
    ]
