# Generated by Django 5.2.8 on 2026-01-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_stockentry_options_alter_item_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="total_quantity",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="acknowledgment_details",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="is_cross_location",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="is_upward_transfer",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="requires_acknowledgment",
        ),
    ]
