# Generated by Django 5.2.8 on 2026-01-22 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_item_total_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentry",
            name="is_in_transit_recorded",
            field=models.BooleanField(
                default=False,
                help_text="True if in_transit_quantity has been updated for this entry",
            ),
        ),
        migrations.AddField(
            model_name="stockentry",
            name="is_stock_recorded",
            field=models.BooleanField(
                default=False,
                help_text="True if physical quantity balances have been updated for this entry",
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="in_transit_quantity",
            field=models.IntegerField(
                default=0,
                help_text="Stock issued from here but not yet acknowledged by receiver",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="quantity",
            field=models.IntegerField(
                default=0,
                help_text="Total stock held at this location (including in-transit)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
