# Generated by Django 5.2.8 on 2026-01-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_stockentry_is_in_transit_recorded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentryitem",
            name="is_in_transit_recorded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockentryitem",
            name="is_stock_recorded",
            field=models.BooleanField(default=False),
        ),
    ]
