# Generated by Django 5.2.8 on 2026-01-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_stockentryitem_is_in_transit_recorded_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockentry",
            name="is_in_transit_recorded",
        ),
        migrations.RemoveField(
            model_name="stockentry",
            name="is_stock_recorded",
        ),
    ]
