# Generated by Django 5.2.8 on 2026-01-22 18:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_stockentry_cancellation_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="allocated_quantity",
            field=models.IntegerField(
                default=0,
                help_text="Stock allocated to persons or non-store locations",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="iteminstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("ISSUED", "Issued"),
                    ("ALLOCATED", "Allocated"),
                    ("IN_USE", "In Use"),
                    ("MAINTENANCE", "In Maintenance"),
                    ("JUNK", "Junked/Disposed"),
                    ("LOST", "Lost"),
                ],
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="entry_type",
            field=models.CharField(
                choices=[("RECEIPT", "Receipt"), ("ISSUE", "Issue")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="in_transit_quantity",
            field=models.IntegerField(
                default=0,
                help_text="Stock in-transit from here to another store",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="quantity",
            field=models.IntegerField(
                default=0,
                help_text="Total physical stock held at this location",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="StockAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ALLOCATED", "Allocated"),
                            ("RETURNED", "Returned"),
                            ("CONSUMED", "Consumed"),
                        ],
                        default="ALLOCATED",
                        max_length=20,
                    ),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "allocated_to_location",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_store": False},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_allocations",
                        to="inventory.location",
                    ),
                ),
                (
                    "allocated_to_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="inventory.person",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.itembatch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="inventory.item",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        limit_choices_to={"is_store": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_allocations",
                        to="inventory.location",
                    ),
                ),
                (
                    "stock_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="inventory.stockentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-allocated_at"],
            },
        ),
    ]
