# Generated by Django 5.2.8 on 2026-01-24 19:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_stockrecord_allocated_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("contract_no", models.CharField(max_length=100, unique=True)),
                ("contract_date", models.DateField(blank=True, null=True)),
                ("contractor_name", models.CharField(max_length=255)),
                ("contractor_address", models.TextField(blank=True, null=True)),
                ("indenter", models.CharField(max_length=150)),
                ("indent_no", models.CharField(max_length=100)),
                ("date_of_delivery", models.DateField(blank=True, null=True)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("PART", "Part"), ("FULL", "Full")],
                        default="FULL",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "inspected_by",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("date_of_inspection", models.DateField(blank=True, null=True)),
                (
                    "consignee_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "consignee_designation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                            ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                            ("AUDIT_REVIEW", "Audit Review (Stage 4)"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("stock_filled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "central_store_filled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("auditor_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "rejection_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                            ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                            ("AUDIT_REVIEW", "Audit Review (Stage 4)"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auditor_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_reviewed_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "central_store_filled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="central_filled_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        limit_choices_to={"is_standalone": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="inventory.location",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_filled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_filled_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_description", models.TextField()),
                ("item_specifications", models.TextField(blank=True, null=True)),
                (
                    "tendered_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("accepted_quantity", models.PositiveIntegerField(default=0)),
                ("rejected_quantity", models.PositiveIntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "stock_register_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stock_register_page_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("stock_entry_date", models.DateField(blank=True, null=True)),
                (
                    "central_register_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "central_register_page_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "inspection_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.inspectioncertificate",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_items",
                        to="inventory.item",
                    ),
                ),
            ],
        ),
    ]
