# Generated by Django 5.2.8 on 2026-01-24 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_inspectioncertificate_inspectionitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="inspectioncertificate",
            old_name="auditor_reviewed_at",
            new_name="finance_reviewed_at",
        ),
        migrations.RemoveField(
            model_name="inspectioncertificate",
            name="auditor_reviewed_by",
        ),
        migrations.AddField(
            model_name="inspectioncertificate",
            name="finance_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_reviewed_inspections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inspectioncertificate",
            name="rejection_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INITIATED", "Initiated"),
                    ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                    ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                    ("FINANCE_REVIEW", "Finance Review (Stage 4)"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inspectioncertificate",
            name="stage",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                    ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                    ("FINANCE_REVIEW", "Finance Review (Stage 4)"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                default="INITIATED",
                max_length=20,
            ),
        ),
    ]
