# Generated by Django 5.2.8 on 2026-01-25 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0016_rename_auditor_reviewed_at_inspectioncertificate_finance_reviewed_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentry",
            name="inspection_certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_entries",
                to="inventory.inspectioncertificate",
            ),
        ),
        migrations.AlterField(
            model_name="inspectioncertificate",
            name="rejection_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("INITIATED", "Initiated (Stage 1)"),
                    ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                    ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                    ("FINANCE_REVIEW", "Finance Review (Stage 4)"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inspectioncertificate",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("INITIATED", "Initiated (Stage 1)"),
                    ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                    ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                    ("FINANCE_REVIEW", "Finance Review (Stage 4)"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inspectioncertificate",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
