# Generated by Django 6.0.1 on 2026-01-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_stockentry_inspection_certificate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inspectioncertificate",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("initiate_inspection", "Can initiate inspection"),
                    ("fill_stock_details", "Can fill stock details (Stage 2)"),
                    ("fill_central_register", "Can fill central register (Stage 3)"),
                    ("review_finance", "Can perform finance review (Stage 4)"),
                ],
            },
        ),
    ]
