# Generated by Django 5.2.8 on 2026-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_movementhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "manage_all_locations",
                        "Can access all locations regardless of hierarchy",
                    ),
                    ("create_standalone_location", "Can create standalone locations"),
                    ("create_store_location", "Can create store locations"),
                    (
                        "view_global_distribution",
                        "Can view item distribution university-wide",
                    ),
                    (
                        "view_scoped_distribution",
                        "Can view item distribution within assigned scope",
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="inspectioncertificate",
            name="rejection_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                    ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                    ("FINANCE_REVIEW", "Finance Review (Stage 4)"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inspectioncertificate",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                    ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                    ("FINANCE_REVIEW", "Finance Review (Stage 4)"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
