# Generated by Django 5.2.8 on 2026-01-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectioncertificate",
            name="finance_check_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
