# Generated by Django 5.2.8 on 2026-01-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_inspectioncertificate_finance_check_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteminstance",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
