# Generated by Django 5.2.8 on 2026-01-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_iteminstance_qr_code_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteminstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("ISSUED", "Issued"),
                    ("ALLOCATED", "Allocated"),
                    ("IN_USE", "In Use"),
                    ("MAINTENANCE", "In Maintenance"),
                    ("JUNK", "Junked/Disposed"),
                    ("LOST", "Lost"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="entry_type",
            field=models.CharField(
                choices=[("RECEIPT", "Receipt"), ("ISSUE", "Issue")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_ACK", "Pending Acknowledgment"),
                    ("COMPLETED", "Completed"),
                    ("PARTIALLY_ACCEPTED", "Partially Accepted"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
