# Generated by Django 5.2.8 on 2026-02-11 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_alter_iteminstance_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteminstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("IN_TRANSIT", "In Transit"),
                    ("ISSUED", "Issued"),
                    ("ALLOCATED", "Allocated"),
                    ("IN_USE", "In Use"),
                    ("MAINTENANCE", "In Maintenance"),
                    ("JUNK", "Junked/Disposed"),
                    ("LOST", "Lost"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("RECEIPT", "Receipt"),
                    ("ISSUE", "Issue"),
                    ("RETURN", "Return"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stockentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_ACK", "Pending Acknowledgment"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StockRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_number", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="The store this register belongs to.",
                        limit_choices_to={"is_store": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_registers",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Register",
                "verbose_name_plural": "Stock Registers",
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_stock_register", "Can add/edit/delete stock registers")
                ],
                "unique_together": {("register_number", "store")},
            },
        ),
    ]
