# Generated by Django 5.2.8 on 2026-02-11 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0024_alter_iteminstance_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentryitem",
            name="ack_page_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Page number in the destination stock register (filled at acknowledgment).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockentryitem",
            name="ack_stock_register",
            field=models.ForeignKey(
                blank=True,
                help_text="The register this entry was recorded in (destination/receiver side, filled at acknowledgment).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dest_items",
                to="inventory.stockregister",
            ),
        ),
        migrations.AddField(
            model_name="stockentryitem",
            name="page_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Page number in the source stock register."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockentryitem",
            name="stock_register",
            field=models.ForeignKey(
                default=1,
                help_text="The register this entry was recorded in (source/sender side).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_items",
                to="inventory.stockregister",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockregister",
            name="register_type",
            field=models.CharField(
                choices=[
                    ("CSR", "Consumable Stock Register"),
                    ("DSR", "Dead Stock Register"),
                ],
                default="CSR",
                max_length=3,
            ),
        ),
    ]
