# Generated by Django 5.2.8 on 2026-02-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_stockentryitem_ack_page_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionitem",
            name="central_register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_items_central",
                to="inventory.stockregister",
            ),
        ),
    ]
