# Generated by Django 5.2.8 on 2026-02-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_inspectionitem_central_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionitem",
            name="stock_register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_items_source",
                to="inventory.stockregister",
            ),
        ),
    ]
