# Generated by Django 5.2.8 on 2026-02-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_inspectiondocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockentryitem",
            name="page_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Page number in the source stock register.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockentryitem",
            name="stock_register",
            field=models.ForeignKey(
                blank=True,
                help_text="The register this entry was recorded in (source/sender side).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_items",
                to="inventory.stockregister",
            ),
        ),
    ]
