# Generated by Django 5.2.8 on 2026-02-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_null_stock_register_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="standalone_locations",
            field=models.ManyToManyField(
                blank=True, related_name="persons", to="inventory.location"
            ),
        ),
    ]
