# Generated by Django 5.2.8 on 2026-02-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_person_designation_person_standalone_locations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "permissions": [
                    (
                        "can_issue_to_any_person",
                        "Can issue stock to any person university-wide",
                    )
                ]
            },
        ),
    ]
