# Generated by Django 5.2.8 on 2026-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_alter_person_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="employee_id",
        ),
    ]
