# Generated by Django 5.2.8 on 2026-02-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0032_remove_person_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockallocation",
            name="allocated_to_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="inventory.person",
            ),
        ),
    ]
