# Generated by Django 5.2.8 on 2026-02-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_alter_stockallocation_allocated_to_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iteminstance",
            options={
                "permissions": [
                    ("change_item_instance", "Can change item instance details")
                ]
            },
        ),
        migrations.AddField(
            model_name="iteminstance",
            name="inspection_certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_instances",
                to="inventory.inspectioncertificate",
            ),
        ),
    ]
