# Generated by Django 5.2.8 on 2026-04-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_alter_iteminstance_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("view_locations", "Can view locations module"),
                    ("create_locations", "Can create locations module records"),
                    ("edit_locations", "Can edit locations module records"),
                    ("delete_locations", "Can delete locations module records"),
                    (
                        "manage_all_locations",
                        "Can access all locations regardless of hierarchy",
                    ),
                    ("create_standalone_location", "Can create standalone locations"),
                    ("create_store_location", "Can create store locations"),
                    (
                        "view_global_distribution",
                        "Can view item distribution university-wide",
                    ),
                    (
                        "view_scoped_distribution",
                        "Can view item distribution within assigned scope",
                    ),
                ],
            },
        ),
    ]
