# Generated by Django 5.2.8 on 2026-04-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_alter_location_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [
                    ("view_categories", "Can view categories"),
                    ("create_categories", "Can create categories"),
                    ("edit_categories", "Can edit categories"),
                    ("delete_categories", "Can delete categories"),
                ],
                "verbose_name_plural": "Categories",
            },
        ),
    ]
