# Generated by Django 5.2.8 on 2026-04-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "permissions": [
                    ("view_items", "Can view items module"),
                    ("create_items", "Can create items module records"),
                    ("edit_items", "Can edit items module records"),
                    ("delete_items", "Can delete items module records"),
                ]
            },
        ),
    ]
