# Generated by Django 5.2.8 on 2026-04-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0037_alter_item_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockentry",
            options={
                "permissions": [
                    ("view_stock_entries", "Can view stock entries module"),
                    ("create_stock_entries", "Can create stock entries module records"),
                    ("edit_stock_entries", "Can edit stock entries module records"),
                    ("delete_stock_entries", "Can delete stock entries module records"),
                    ("acknowledge_stockentry", "Can acknowledge stock receipt entries"),
                ]
            },
        ),
    ]
