# Generated by Django 5.2.8 on 2026-04-25 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0038_alter_stockentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockentryitem",
            name="accepted_instances",
            field=models.ManyToManyField(
                blank=True,
                help_text="Instances accepted by the destination during acknowledgment. Original instances are preserved for audit.",
                related_name="accepted_stock_entry_items",
                to="inventory.iteminstance",
            ),
        ),
        migrations.AddField(
            model_name="stockentryitem",
            name="accepted_quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantity accepted by the destination during acknowledgment. Original quantity is preserved for audit.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
