# Generated by Django 5.2.8 on 2026-04-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0039_stockentryitem_accepted_instances_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockregister",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_stock_registers", "Can view stock registers module"),
                    ("create_stock_registers", "Can create stock registers module records"),
                    ("edit_stock_registers", "Can edit stock registers module records"),
                    ("delete_stock_registers", "Can delete stock registers module records"),
                    ("manage_stock_register", "Can add/edit/delete stock registers"),
                ],
                "verbose_name": "Stock Register",
                "verbose_name_plural": "Stock Registers",
            },
        ),
    ]
