# Generated by Django 5.2.8 on 2026-04-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0044_quantity_tracking_and_instance_batches"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionitem",
            name="manufactured_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
