# Generated by Django 5.2.8 on 2026-04-29 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0045_inspectionitem_manufactured_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockentry",
            options={
                "permissions": [
                    ("view_stock_entries", "Can view stock entries module"),
                    ("create_stock_entries", "Can create stock entries module records"),
                    ("edit_stock_entries", "Can edit stock entries module records"),
                    ("delete_stock_entries", "Can delete stock entries module records"),
                    ("acknowledge_stockentry", "Can acknowledge stock receipt entries"),
                    (
                        "approve_stock_corrections",
                        "Can approve stock entry corrections and reversals",
                    ),
                ]
            },
        ),
        migrations.AddField(
            model_name="stockentry",
            name="reference_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AUTO_RECEIPT", "Auto Receipt"),
                    ("REJECTION_RETURN", "Rejection Return"),
                    ("REVERSAL", "Reversal"),
                    ("ADDITIONAL_MOVEMENT", "Additional Movement"),
                    ("REPLACEMENT", "Replacement"),
                    ("ADJUSTMENT", "Adjustment"),
                ],
                db_index=True,
                help_text="Internal reason this entry references another entry.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StockCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("APPLIED", "Applied"),
                            ("REJECTED", "Rejected"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_type",
                    models.CharField(
                        choices=[
                            ("NO_CHANGE", "No Change"),
                            ("ADDITIONAL_MOVEMENT", "Additional Movement"),
                            ("REVERSAL", "Reversal"),
                            ("ALLOCATION_INCREASE", "Allocation Increase"),
                            ("ALLOCATION_REDUCTION", "Allocation Reduction"),
                            ("RETURN_INCREASE", "Return Increase"),
                            ("RETURN_REDUCTION", "Return Reduction"),
                            ("ADJUSTMENT_REQUIRED", "Adjustment Required"),
                            ("MIXED", "Mixed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="NO_CHANGE",
                        max_length=40,
                    ),
                ),
                ("reason", models.TextField()),
                ("message", models.TextField(blank=True, default="")),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_stock_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_entries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="generated_by_correction_requests",
                        to="inventory.stockentry",
                    ),
                ),
                (
                    "original_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_requests",
                        to="inventory.stockentry",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_stock_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_stock_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCorrectionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_quantity", models.PositiveIntegerField()),
                ("corrected_quantity", models.PositiveIntegerField()),
                ("delta", models.IntegerField()),
                (
                    "affected_instances",
                    models.ManyToManyField(
                        blank=True,
                        related_name="correction_lines",
                        to="inventory.iteminstance",
                    ),
                ),
                (
                    "original_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="correction_lines",
                        to="inventory.stockentryitem",
                    ),
                ),
                (
                    "correction_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockcorrectionrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
