# Generated by Django 5.2.8 on 2026-04-30 18:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0046_stock_correction_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepreciationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="FBR WDV", max_length=150, unique=True),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("WDV", "Written Down Value")],
                        default="WDV",
                        max_length=20,
                    ),
                ),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(default=7),
                ),
                ("fiscal_year_start_day", models.PositiveSmallIntegerField(default=1)),
                ("is_default", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_depreciation_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationAssetClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depreciation_asset_classes",
                        to="inventory.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_depreciation_asset_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_classes",
                        to="inventory.depreciationpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationRateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "source_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_depreciation_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_versions",
                        to="inventory.depreciationassetclass",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_depreciation_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["asset_class", "-effective_from", "-created_at"],
                "unique_together": {("asset_class", "effective_from")},
            },
        ),
        migrations.CreateModel(
            name="DepreciationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year_start", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_depreciation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="inventory.depreciationpolicy",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_depreciation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_depreciation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fiscal_year_start", "-created_at"],
                "unique_together": {("policy", "fiscal_year_start")},
            },
        ),
        migrations.CreateModel(
            name="FixedAssetRegisterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("INSTANCE", "Individual Instance"),
                            ("LOT", "Quantity Lot"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_quantity", models.PositiveIntegerField(default=1)),
                ("remaining_quantity", models.PositiveIntegerField(default=1)),
                (
                    "original_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("capitalization_date", models.DateField()),
                ("depreciation_start_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISPOSED", "Disposed"),
                            ("LOST", "Lost"),
                            ("JUNK", "Junked"),
                            ("INACTIVE", "Inactive"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="inventory.depreciationassetclass",
                    ),
                ),
                (
                    "batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_asset_entry",
                        to="inventory.itembatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fixed_asset_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspection_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_asset_entries",
                        to="inventory.inspectionitem",
                    ),
                ),
                (
                    "instance",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_asset_entry",
                        to="inventory.iteminstance",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_asset_entries",
                        to="inventory.item",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="inventory.depreciationpolicy",
                    ),
                ),
                (
                    "source_inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_asset_entries",
                        to="inventory.inspectioncertificate",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_number", "id"],
                "permissions": [
                    ("view_depreciation", "Can view depreciation module"),
                    (
                        "manage_depreciation",
                        "Can create and edit depreciation profiles and adjustments",
                    ),
                    (
                        "post_depreciation",
                        "Can configure rates and post depreciation runs",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetValueAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("ADDITION", "Capital Addition"),
                            ("COST_CORRECTION", "Cost Correction"),
                            ("DISPOSAL", "Disposal"),
                            ("LOSS", "Loss"),
                            ("WRITE_OFF", "Write-off"),
                            ("QUANTITY_REDUCTION", "Quantity Reduction"),
                        ],
                        max_length=30,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("quantity_delta", models.IntegerField(default=0)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_asset_value_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.fixedassetregisterentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year_start", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("opening_value", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "depreciation_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("closing_value", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rate_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_entries",
                        to="inventory.depreciationrateversion",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="inventory.depreciationrun",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_entries",
                        to="inventory.fixedassetregisterentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-fiscal_year_start", "asset__asset_number"],
                "unique_together": {("asset", "fiscal_year_start", "run")},
            },
        ),
    ]
