# Generated by Django 5.2.8 on 2026-04-30 18:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0047_depreciation_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionitem",
            name="capitalization_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="inspectionitem",
            name="capitalization_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspectionitem",
            name="depreciation_asset_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspection_items",
                to="inventory.depreciationassetclass",
            ),
        ),
    ]
