# Generated by Django 5.2.8 on 2026-05-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0049_alter_location_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_provisional",
            field=models.BooleanField(
                default=False,
                help_text="Hidden from the catalog until the owning inspection certificate is completed.",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="provisional_inspection",
            field=models.ForeignKey(
                blank=True,
                help_text="Inspection workflow that owns this provisional item until completion.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provisional_items",
                to="inventory.inspectioncertificate",
            ),
        ),
    ]
