# Generated by Django 5.2.8 on 2026-05-03 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0050_item_is_provisional_item_provisional_inspection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectioncertificate",
            name="revision_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspectioncertificate",
            name="revision_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revision_requested_inspections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inspectioncertificate",
            name="revision_requested_from_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("STOCK_DETAILS", "Stock Details (Stage 2)"),
                    ("CENTRAL_REGISTER", "Central Register (Stage 3)"),
                    ("FINANCE_REVIEW", "Finance Review (Stage 4)"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inspectioncertificate",
            name="revision_requested_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
