# Generated by Django 5.2.8 on 2026-05-06 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0052_maintenancemeterreading_maintenanceplan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assetvalueadjustment",
            index=models.Index(
                fields=["asset", "effective_date"], name="assetadjust_asset_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depreciationentry",
            index=models.Index(
                fields=["asset", "-fiscal_year_start"], name="depentry_asset_latest_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="depreciationrateversion",
            index=models.Index(
                fields=["asset_class", "-effective_from", "-created_at"],
                name="depr_rate_class_latest_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fixedassetregisterentry",
            index=models.Index(
                fields=["status", "item"], name="fixedasset_status_item_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixedassetregisterentry",
            index=models.Index(
                fields=["policy", "status", "capitalization_date"],
                name="fixedasset_run_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectioncertificate",
            index=models.Index(fields=["stage"], name="inspection_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="inspectioncertificate",
            index=models.Index(fields=["status"], name="inspection_status_idx"),
        ),
        migrations.AddIndex(
            model_name="inspectioncertificate",
            index=models.Index(
                fields=["department", "stage"], name="inspection_dept_stage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockallocation",
            index=models.Index(
                fields=["status", "source_location", "item", "batch"],
                name="stockalloc_stat_src_item_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockallocation",
            index=models.Index(
                fields=["stock_entry", "item", "batch"],
                name="stockalloc_entry_item_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockallocation",
            index=models.Index(
                fields=["status", "allocated_to_person"],
                name="stockalloc_stat_person_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockallocation",
            index=models.Index(
                fields=["status", "allocated_to_location"],
                name="stockalloc_stat_loc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockrecord",
            index=models.Index(
                fields=["location", "item", "batch"], name="stockrec_loc_item_batch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockrecord",
            index=models.Index(
                fields=["item", "location", "batch"], name="stockrec_item_loc_batch_idx"
            ),
        ),
    ]
