# Generated by Django 5.2.8 on 2026-05-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0056_alter_location_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "permissions": [
                    ("view_employees", "Can view employees module"),
                    ("create_employees", "Can create employees module records"),
                    ("edit_employees", "Can edit employees module records"),
                    ("delete_employees", "Can delete employees module records"),
                    (
                        "can_issue_to_any_person",
                        "Can issue stock to any person university-wide",
                    ),
                ],
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="perse_number",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
