# Generated by Django 5.2.8 on 2026-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0059_stock_reconciliation_audit_voided_stockentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(blank=True, max_length=64, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BUILDING", "Building"),
                            ("DEAN_FACULTY", "Dean Faculty"),
                            ("DEPARTMENT_NATURE", "Department Nature"),
                            ("CAMPUS_ZONE", "Campus Zone"),
                            ("USAGE_TYPE", "Usage Type"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=40,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="inventory_l_code_ab5ced_idx"),
                    models.Index(
                        fields=["category"], name="inventory_l_categor_edf890_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="inventory_l_is_acti_80c57e_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="location",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reporting/grouping tags. Does not affect hierarchy or permissions.",
                related_name="locations",
                to="inventory.locationtag",
            ),
        ),
    ]
