# Generated by Django 5.2.8 on 2026-05-25 11:02

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_merge_item_hybrid_search_stock_reconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='embedded_text_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 of the text that produced the current embedding. Used to skip redundant re-embeds on no-op saves.', max_length=64),
        ),
        migrations.AlterField(
            model_name='item',
            name='search_text',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Weighted Postgres tsvector for BM25-style ranking. Maintained by the post_save signal. Unused on SQLite.', null=True),
        ),
    ]
