"""
Django settings for ams project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# ENVIRONMENT DETECTION
# =============================================================================
ENVIRONMENT = config('ENVIRONMENT', default='development')
IS_PRODUCTION = ENVIRONMENT == 'production'


# =============================================================================
# SECURITY
# =============================================================================
SECRET_KEY = config('SECRET_KEY')

DEBUG = not IS_PRODUCTION

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
    'corsheaders',
    'inventory',
    'user_management',
    'notifications',
    'ai_assistant',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ENABLE_SILK = config('ENABLE_SILK', default=False, cast=bool)
if ENABLE_SILK:
    INSTALLED_APPS.append('silk')
    MIDDLEWARE.insert(1, 'silk.middleware.SilkyMiddleware')
    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True
    SILKY_PERMISSIONS = lambda user: bool(user and user.is_superuser)


ROOT_URLCONF = 'ams.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ams.wsgi.application'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =============================================================================
# DATABASE
# =============================================================================
# Database selection — decoupled from IS_PRODUCTION so a developer can run
# the local app in production-like mode (DEBUG off, secure cookies) while
# still pointing at SQLite, OR run in development mode against Postgres for
# hybrid-search testing. USE_POSTGRES defaults to IS_PRODUCTION for backwards
# compatibility with the existing prod deploy that relied on the implicit
# coupling. Override either independently via .env.
USE_POSTGRES = config('USE_POSTGRES', default=IS_PRODUCTION, cast=bool)

if USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
            'ATOMIC_REQUESTS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,
            },
            'ATOMIC_REQUESTS': True,
        }
    }


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =============================================================================
# STATIC & MEDIA FILES
# =============================================================================
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =============================================================================
# REST FRAMEWORK
# =============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'ams.cookie_auth.JWTCookieAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',
        'user': '200/minute',
    },
}


# =============================================================================
# SIMPLE JWT
# =============================================================================
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# =============================================================================
# CORS
# =============================================================================
CORS_ALLOW_CREDENTIALS = True

if IS_PRODUCTION:
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())
else:
    CORS_ALLOWED_ORIGINS = config(
        'CORS_ALLOWED_ORIGINS',
        default='http://localhost:3000,http://127.0.0.1:3000',
        cast=Csv(),
    )


# =============================================================================
# FRONTEND URL (QR codes, links)
# =============================================================================
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

COOKIE_SECURE = config(
    'COOKIE_SECURE',
    default=IS_PRODUCTION and urlparse(FRONTEND_URL).scheme.lower() == 'https',
    cast=bool,
)

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default=FRONTEND_URL if IS_PRODUCTION else 'http://localhost:3000,http://127.0.0.1:3000',
    cast=Csv(),
)


# =============================================================================
# DJOSER (AUTH)
# =============================================================================
DJOSER = {
    'LOGIN_FIELD': 'username',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'SERIALIZERS': {
        'user_create': 'user_management.serializers.RegisterSerializer',
        'user': 'user_management.serializers.UserSerializer',
        'current_user': 'user_management.serializers.UserSerializer',
    },
    'PERMISSIONS': {
        'user_create': ['ams.permissions.DjoserUserCreateDisabled'],
        'user': ['rest_framework.permissions.IsAuthenticated'],
        'user_list': ['rest_framework.permissions.IsAuthenticated'],
        'token_create': ['rest_framework.permissions.AllowAny'],
    },
}


# =============================================================================
# PRODUCTION SECURITY HARDENING
# =============================================================================
if IS_PRODUCTION:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_SECURE = COOKIE_SECURE
    CSRF_COOKIE_SECURE = COOKIE_SECURE


# =============================================================================
# COPILOT HYBRID ITEM SEARCH (agent-only Central Register linking)
# =============================================================================
# Postgres-only. SQLite dev installs skip the embedding columns and the
# copilot endpoint falls back to standard keyword search.
ITEM_SEARCH_HYBRID_ENABLED = config(
    'ITEM_SEARCH_HYBRID_ENABLED', default=False, cast=bool,
)

# Embedding provider — OpenAI-compatible HTTP API. Wire to OpenRouter for
# testing by pointing EMBEDDING_BASE_URL at OpenRouter and using one of
# their hosted embedding models.
EMBEDDING_BASE_URL = config(
    'EMBEDDING_BASE_URL', default='https://openrouter.ai/api/v1',
)
EMBEDDING_API_KEY = config('EMBEDDING_API_KEY', default='')
EMBEDDING_MODEL = config(
    'EMBEDDING_MODEL', default='openai/text-embedding-3-small',
)
EMBEDDING_DIM = config('EMBEDDING_DIM', default=1536, cast=int)
EMBEDDING_TIMEOUT_SECONDS = config(
    'EMBEDDING_TIMEOUT_SECONDS', default=15, cast=int,
)

# RRF (Reciprocal Rank Fusion) constant — Cormack et al. recommend 60.
ITEM_SEARCH_RRF_K = config('ITEM_SEARCH_RRF_K', default=60, cast=int)

# Per-stage candidate budgets before fusion.
ITEM_SEARCH_BM25_TOP_N = config('ITEM_SEARCH_BM25_TOP_N', default=30, cast=int)
ITEM_SEARCH_SEMANTIC_TOP_N = config(
    'ITEM_SEARCH_SEMANTIC_TOP_N', default=30, cast=int,
)

# Minimum cosine similarity for SEMANTIC-ONLY candidates. pgvector ranks every
# embedded item by distance, so without a floor the result tail is just
# "nearest available" noise rather than actual matches. Hits that also matched
# BM25 are kept regardless — lexical agreement is evidence enough. 0 disables.
ITEM_SEARCH_MIN_SEMANTIC_SCORE = config(
    'ITEM_SEARCH_MIN_SEMANTIC_SCORE', default=0.35, cast=float,
)

